# shellcheck shell=bash
#
# lib/trigger-linux.sh -- install/remove a udev rule + systemd service that runs
# a backup when a drive is plugged in. Sourced by setup.sh on Linux only.
#
# Two decisions worth stating, because the obvious alternatives are wrong:
#
# 1. The backup is NEVER run from udev directly. udev kills long-running RUN+=
#    children and blocks its own event queue while they live. The rule only
#    pulls in a systemd service, which then outlives the event.
#
# 2. We do NOT take over mounting. The desktop (udisks2) already automounts the
#    drive, and a systemd .mount unit fighting it causes the drive to appear and
#    then instantly vanish whenever the backup declines to run -- exactly what
#    happens during a cooldown. Instead the service waits briefly for udisks to
#    finish and asks findmnt where the drive landed.

linux_unit_name()  { printf 'rsync-backup@%s.service' "$1"; }
linux_rule_path()  { printf '/etc/udev/rules.d/95-rsync-backup-%s.rules' "$1"; }
linux_unit_path()  { printf '/etc/systemd/system/rsync-backup@.service'; }
linux_wait_path()  { printf '%s/lib/wait-for-mount.sh' "$1"; }

# linux_trigger_files NAME REPO_ROOT UUID USER -- prints the three artefacts to
# stdout as a shell script the user can inspect and run with sudo. setup.sh
# never silently escalates.
linux_trigger_emit() {
    _lt_name=$1
    _lt_repo=$2
    _lt_uuid=$3
    _lt_user=$4
    _lt_rule=$(linux_rule_path "$_lt_name")
    _lt_unit=$(linux_unit_path)

    cat <<EOF
#!/bin/bash
# Generated by setup.sh for backup '$_lt_name'. Review, then run with sudo.
# Removes cleanly with: sudo rm -f $_lt_rule && sudo systemctl daemon-reload
set -euo pipefail

# --- 1. the templated service -------------------------------------------------
# Type=oneshot so systemd tracks it to completion; the udev event is long gone.
# It runs as $_lt_user because the backup reads that user's home and the repo
# lives there. RemainAfterExit=no keeps it out of the way once finished.
cat > '$_lt_unit' <<'UNIT'
[Unit]
Description=rsync backup triggered by drive connect (%i)
# The drive is mounted by udisks, not by us, so there is nothing to require here.

[Service]
Type=oneshot
User=$_lt_user
Nice=10
# Wait for udisks to finish mounting, then run. The wait is bounded; if the
# drive never appears the runner's own guard refuses to write to the system disk.
ExecStart=/bin/bash $(linux_wait_path "$_lt_repo") %i
TimeoutStartSec=0
UNIT

# --- 2. the udev rule ---------------------------------------------------------
# Matched on the filesystem UUID, so only THIS drive triggers it. 95- runs late,
# after udisks has seen the device. SYSTEMD_WANTS hands off and returns
# immediately -- udev must never wait for a backup.
cat > '$_lt_rule' <<'RULE'
ACTION=="add", SUBSYSTEM=="block", ENV{ID_FS_UUID}=="$_lt_uuid", \\
  ENV{SYSTEMD_WANTS}="rsync-backup@$_lt_name.service", TAG+="systemd"
RULE

# --- 3. reload ----------------------------------------------------------------
systemctl daemon-reload
udevadm control --reload-rules

echo
echo "Installed:"
echo "  $_lt_rule"
echo "  $_lt_unit"
echo
echo "Nothing to 'systemctl enable' -- the rule pulls the service in on connect."
echo "Test without replugging:"
echo "  sudo systemctl start 'rsync-backup@$_lt_name.service'"
echo "  journalctl -u 'rsync-backup@$_lt_name.service' -n 30 --no-pager"
EOF
}

# linux_trigger_status NAME
linux_trigger_status() {
    _ls_rule=$(linux_rule_path "$1")
    if [ -f "$_ls_rule" ]; then
        printf 'installed (%s)' "$_ls_rule"
    else
        printf 'NOT installed'
    fi
}

# linux_volume_identity MOUNTPOINT -- exFAT reports a 32-bit volume serial such
# as 6A77-25FC here, NOT a real UUID. That is expected; it simply differs from
# the string macOS records for the same drive.
linux_volume_identity() {
    findmnt -no UUID --target "$1" 2>/dev/null
}
